version: "3.7"
services:
  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1973
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    network_mode: host
    ports:
      - "8080:8080"
