spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasks_db
    username: postgres
    password: "1973"
telegram:
  botName: todo_task_manager_bot
  token: 5893091443:AAE0sC4VKHILLmvdgREQrBFv7eCUKLtF83o